### ISSUE TITLE
Data Structure Design

### ISSUE THREAD

**Issue by VatsalJagani** [VatsalJagani/Battleship#5]
Description : Data structure for storing ships location at server side.
Estimation : 1 HR
Priority : 5 (out of 5)

**Comment by meetdave2611997** [comment]
nested list is used to store data of coordinates of ships.
server accepts a specific type of string from client which server parses and pushes coordinates of ships in list
'|' is used to separate ships
',' is used to separate coordinates of particular ship
example:- 1,2,3|4,5|9
which in turn will be stored into list like this:
[[1,2,3],[4,5],[9]]
